DATA_DIR=

TRAIN_IMAGE_PATH=
TRAIN_LABEL_PATH=
TRAIN_FEATURE_PATH=

VAL_IMAGE_PATH=
VAL_LABEL_PATH=
VAL_FEATURE_PATH=

TEST_IMAGE_PATH=
TEST_LABEL_PATH=
TEST_FEATURE_PATH=


MODEL_DIR=
EXPORTED_MODEL_PATH=

python demo_getdata.py $TRAIN_IMAGE_PATH $TRAIN_LABEL_PATH $VAL_IMAGE_PATH $VAL_LABEL_PATH $TEST_IMAGE_PATH $TEST_LABEL_PATH
python demo_train.py $EXPORTED_MODEL_PATH $TRAIN_FEATURE_PATH $VAL_FEATURE_PATH